export default {
  ADHD: { toString: () => 'ADHD' },
  ANGER_AGRESSION: { toString: () => 'Anger/Aggression' },
  ANXIETY: { toString: () => 'Anxiety' },
  AUTISM_SPECTRUM: { toString: () => 'Autism Spectrum' },
  BI_POLAR: { toString: () => 'Bi-Polar' },
  DEPRESSION: { toString: () => 'Depression' },
  DRUG_ALCOHOL: { toString: () => 'Drug/Alcohol' },
  EXPLOSIVE_DISORDER: { toString: () => 'Explosive Disorder' },
  IEP: { toString: () => 'IEP' },
  MOOD_DISORDER: { toString: () => 'Mood Disorder' },
  ODD: { toString: () => 'ODD' },
  OTHER: { toString: () => 'Other' },
  PTSD: { toString: () => 'PTSD' },
  PSYCHIATRIC: { toString: () => 'Psychiatric' },
  SPECIAL_EDUCATION: { toString: () => 'Special Education' },
  UNSPECIFIED: { toString: () => 'Unspecified' },
};
