export default {
  ADULT: { toString: () => 'Adult' },
  CUA: { toString: () => 'CUA' },
  DEPENDENT_PLACEMENT: { toString: () => 'Dependent Placement' },
  DETENTION_BW: { toString: () => 'Detention Bench Warrant' },
  DETENTION_NON_RESPITE: { toString: () => 'Detention Non-Respite' },
  DETENTION_RESPITE: { toString: () => 'Detention Respite' },
  DIVERSION: { toString: () => 'Diversion' },
  DONT_FALL_DOWN_IN_THE_HOOD: { toString: () => "Don't Fall Down in the Hood" },
  GPS: { toString: () => 'GPS' },
  GROUP_HOME_DELINQUENT: { toString: () => 'Group Home Delinquent' },
  GROUP_HOME_DEPENDENT: { toString: () => 'Group Home Dependent' },
  HOSPITAL_MENTAL_HEALTH: { toString: () => 'Hospital - Mental Health' },
  HOSPITAL_PHYSICAL_HEALTH: { toString: () => 'Hospital - Physical Health' },
  IHD: { toString: () => 'IHD' },
  INPATIENT_DRUG: { toString: () => 'Inpatient D&A' },
  IPS: { toString: () => 'IPS' },
  ISP: { toString: () => 'ISP' },
  OTHER: { toString: () => 'Other' },
  PLACEMENT: { toString: () => 'Placement' },
  POST_ERC: { toString: () => 'Post-ERC' },
  PRE_ERC: { toString: () => 'Pre-ERC' },
  PYAP_75: { toString: () => 'PYAP 7.5' },
  REINTEGRATION: { toString: () => 'Reintegration' },
  RTF: { toString: () => 'RTF' },
};
