export default {
  HOME_BROTHER: { toString: () => 'Home - Brother' },
  HOME_CONGREGATE: { toString: () => 'Home - Congregate' },
  HOME_FATHER: { toString: () => 'Home - Father' },
  HOME_MOTHER: { toString: () => 'Home - Mother' },
  HOME_MULTIPLE: { toString: () => 'Home - Multiple' },
  HOME_OTHER: { toString: () => 'Home - Other' },
  HOME_PROPERTY: { toString: () => 'Home - Property' },
  HOME_SIBLINGS: { toString: () => 'Home - Siblings' },
  HOME_SISTER: { toString: () => 'Home - Sister' },
  SCHOOL_DRUGS: { toString: () => 'School - Drugs' },
  SCHOOL_OTHER: { toString: () => 'School - Other' },
  SCHOOL_OTHER_STUDENT: { toString: () => 'School - Other Student' },
  SCHOOL_POLICE_CLIMATE_STAFF: {
    toString: () => 'School - Police/Climate Staff',
  },
  SCHOOL_PROPERTY: { toString: () => 'School - Property' },
  SCHOOL_TEACHING_STAFF: { toString: () => 'School - Teaching Staff' },
  SCHOOL_TERRORISTIC_THREAT: { toString: () => 'School - Terroristic Threat' },
  SCHOOL_WEAPON: { toString: () => 'School - Weapon' },
};
