export default [
  'Academy @ Palumbo',
  'Arts Academy @ Benjamin Rush',
  'Bartram, John',
  'Bodine, William W.',
  'Building 21',
  'Carver Engineering & Science',
  'Central',
  'Constitution',
  'Creative & Performing Arts',
  'Dobbins, Murrell',
  'Edison, Thomas A.',
  'Fels, Samuel',
  'Frankford',
  'Franklin Learning Center',
  'Franklin, Benjamin',
  'Franklin, Benjamin EOP',
  'Furness, Horace',
  'Girard Academic Music Program',
  'Kensington',
  'Kensington CAPA',
  'Kensington Health Sciences',
  'King, Martin Luther',
  'Lankenau',
  'Lincoln, Abraham',
  'Mastbaum, Jules E.',
  'Masterman, Julia R.',
  'Motivation',
  'Northeast',
  'Overbrook',
  'Parkway Center City',
  'Parkway Northwest',
  'Parkway West',
  'Penn Treaty',
  'Philadelphia High School for Girls',
  'Philadelphia Learning Academy – North',
  'Philadelphia Learning Academy – North EOP',
  'Philadelphia Learning Academy – South',
  'Philadelphia Learning Academy – South EOP',
  'Philadelphia Military Academy',
  'Philadelphia Virtual Academy',
  'Randolph Technical',
  'Robeson, Paul',
  'Roxborough',
  'Saul, Walter B.',
  'Sayre, William L.',
  'School of the Future',
  'Science Leadership Academy',
  'Science Leadership Academy @ Beeber',
  'South Philadelphia',
  'Strawberry Mansion',
  'Swenson Arts/Tech',
  'The LINC',
  'U School',
  'Vaux Big Picture',
  'Washington, George',
  'West Philadelphia',
  'Workshop School',
];
